version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=dam_analytics.settings
    volumes:
      - .:/app
    command: gunicorn dam_analytics.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: dam_db
      POSTGRES_USER: dam_user
      POSTGRES_PASSWORD: dam_password
    ports:
      - "5433:5432"  # Map to a different port on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
