# Generated by Django 5.1 on 2024-08-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.FloatField()),
                ('inflow', models.FloatField()),
                ('power_house_discharge', models.FloatField()),
                ('spillway_release', models.FloatField()),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='dams.dam')),
            ],
            options={
                'unique_together': {('dam', 'date')},
            },
        ),
    ]
