# Generated by Django 5.1 on 2024-08-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damstatistics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dams.dam'),
        ),
    ]
